### ISSUE TITLE
Github - How to get Galaxy Brain Achievement in Github?

### ISSUE THREAD

**Issue by HappyCodingLover** [SWS-5007/My-Experience#25]
Hello, Everyone.
Here is one question.
How to get Galaxy Brain Achievement in Github?
If you have any experience for this field, please help me.
Thanks

**Comment by SWS-5007** [comment]
We currently assume it's
"You need to become the marked answer to 2 discussions?"
But it seems like there are more conditions, for example you don't seem to be able to mark yourself as the answer.

But I invite you to select this as the answer, because then I should have answered 2 discussions (which I didn't create myself) and be marked by the OP as the answer, soooo that should yield Galaxy Brain, hopefully.

To check more details, please check this link.
[https://github.com/Schweinepriester/github-profile-achievements/discussions/9#discussioncomment-2927413](https://github.com/Schweinepriester/github-profile-achievements/discussions/9#discussioncomment-2927413)

I hope this will be helpful for you too.
Thanks.
